import { useState, useEffect, Fragment } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import AboutUs from "../components/About Us";
import Tabs from "../components/Tabs";
import WhyUs from "../components/Why Us";
import Video from "../components/Video";
import Services from "../components/Services";
import Testimonials from "../components/Testimonials";
import Milestone from "../components/Milestone";
import ContactUs from "../components/Contact Us";
import Footer from "../components/Footer";
import { createClient } from "contentful";

export async function getStaticProps() {
  const client = createClient({
    space: "ekq2l24qwz6g",
    accessToken: "lKmKCfDCDH-rUOQMkKxteCtKOtM0e3wTb_dUF0TbPk4",
  });

  const res = await client.getEntries({ content_type: "madinaMechanical" });
  let apiData = res.items[0].fields;
  const res2 = await client.getEntries({ content_type: "reviews" });
  let reviews = [{ name: "description" }];
  res2.items.forEach((e) => reviews.push(e.fields));
  const res3 = await client.getEntries({ content_type: "info" });
  let info = res3.items[0].fields;

  return {
    props: {
      apiData,
      reviews,
      info,
    },
  };
}

export default function Home({ apiData, reviews, info }) {
  function getWindowDimensions() {
    const { innerWidth: width, innerHeight: height } = window;
    return {
      width,
      height,
    };
  }

  const [windowDimensions, setWindowDimensions] = useState(null);

  useEffect(() => {
    handleResize();
    function handleResize() {
      setWindowDimensions(getWindowDimensions());
    }
    window.addEventListener("resize", handleResize);
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Madina Mechanical Inc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar windowDimensions={windowDimensions} />
        <Header fields={apiData.header} windowDimensions={windowDimensions} />
        <AboutUs fields={apiData.aboutUs} windowDimensions={windowDimensions} />
        <Tabs
          fields={{
            Heating: apiData.heating,
            Ventilation: apiData.airConditioning,
            "Air Conditioning": apiData.ventilation,
          }}
        />
        <WhyUs windowDimensions={windowDimensions} />
        <Video fields={apiData.video} />
        <Services
          fields={apiData.services}
          windowDimensions={windowDimensions}
        />
        <Testimonials reviews={reviews} windowDimensions={windowDimensions} />
        <Milestone info={info} />
        <ContactUs windowDimensions={windowDimensions} />
        <Footer info={info} windowDimensions={windowDimensions} />
      </main>
    </div>
  );
}
